# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
                ('file', models.FileField(upload_to='goods/file')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('articul', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('in_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_2', models.FloatField(blank=True, null=True)),
                ('price_3', models.FloatField(blank=True, null=True)),
                ('price_4', models.FloatField(blank=True, null=True)),
                ('price_5', models.FloatField(blank=True, null=True)),
                ('price_6', models.FloatField(blank=True, null=True)),
                ('price_7', models.FloatField(blank=True, null=True)),
                ('price_8', models.FloatField(blank=True, null=True)),
                ('price_9', models.FloatField(blank=True, null=True)),
                ('price_10', models.FloatField(blank=True, null=True)),
                ('price_11', models.FloatField(blank=True, null=True)),
                ('price_12', models.FloatField(blank=True, null=True)),
                ('price_13', models.FloatField(blank=True, null=True)),
                ('price_14', models.FloatField(blank=True, null=True)),
                ('price_15', models.FloatField(blank=True, null=True)),
                ('price_16', models.FloatField(blank=True, null=True)),
                ('price_17', models.FloatField(blank=True, null=True)),
                ('price_18', models.FloatField(blank=True, null=True)),
                ('price_19', models.FloatField(blank=True, null=True)),
                ('price_20', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NewGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Goods')),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('photo_width', models.IntegerField(default=0)),
                ('photo_height', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods/producers_photos')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='рейтинг')),
                ('visibility', models.BooleanField(db_index=True, default=False, verbose_name='отображать')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='UploadsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_width', models.PositiveSmallIntegerField()),
                ('img_height', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(height_field='img_height', upload_to='goods/image', width_field='img_width')),
            ],
            options={
                'verbose_name': 'Загрузки',
                'verbose_name_plural': 'Загрузки',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Photo'),
        ),
        migrations.AddField(
            model_name='goods',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Producers'),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together=set([('code', 'articul')]),
        ),
    ]
