# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='in_stock',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
