# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price_10',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_11',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_12',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_13',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_14',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_15',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_16',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_17',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_18',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_19',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_20',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_5',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_6',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_7',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_8',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price_9',
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 1'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 10'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 11'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 12'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_13',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 13'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_14',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 14'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_15',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 15'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_16',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 16'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 17'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_18',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 18'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_19',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 19'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 2'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_20',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 20'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 3'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 4'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 5'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 6'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 7'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 8'),
        ),
        migrations.AddField(
            model_name='goods',
            name='opt_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='отп 9'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Розничная цена'),
        ),
    ]
