# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20181019_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='opt_1',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_10',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 10'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_11',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 11'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_12',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 12'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_13',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 13'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_14',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 14'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_15',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 15'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_16',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 16'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_17',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 17'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_18',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 18'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_19',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 19'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_2',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_20',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 20'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_3',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 3'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_4',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 4'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_5',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 5'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_6',
            field=models.FloatField(blank=True, null=True, verbose_name='опт 6'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_7',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 7'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_8',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 8'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='opt_9',
            field=models.FloatField(blank=True, null=True, verbose_name='отп 9'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Розничная цена'),
        ),
    ]
