# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20181024_1306'),
        ('main_page', '0003_auto_20181019_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='filter_lvl_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.LvlOne'),
        ),
        migrations.AddField(
            model_name='goods',
            name='filter_lvl_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.LvlThree'),
        ),
        migrations.AddField(
            model_name='goods',
            name='filter_lvl_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.LvlTwo'),
        ),
    ]
