# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20180816_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('image', models.ImageField(height_field='img_height', upload_to='goods/image', width_field='img_width')),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
