# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20181025_1359'),
        ('main_page', '0004_auto_20181024_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='filter_lvl_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.LvlFive'),
        ),
        migrations.AddField(
            model_name='goods',
            name='filter_lvl_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.LvlFour'),
        ),
    ]
