# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20180829_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadsimage',
            options={'verbose_name': 'Загрузки', 'verbose_name_plural': 'Загрузки'},
        ),
        migrations.AlterField(
            model_name='uploadsimage',
            name='img_height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadsimage',
            name='img_width',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
