# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
