# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='good',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
