# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20180910_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('good', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Goods')),
            ],
        ),
    ]
