# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20180910_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rec_code',
            new_name='ref_code',
        ),
    ]
