# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20180912_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='order_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
