# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_goods_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
