# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20180925_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='price_4',
            new_name='price_6',
        ),
    ]
