# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20180925_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
