# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_producers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producers',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AddField(
            model_name='producers',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Photo'),
        ),
    ]
