# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_auto_20180926_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='excel/')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
