# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_excelimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelimport',
            options={'verbose_name': 'Загрузить_эксел', 'verbose_name_plural': 'Загрузить_эксели'},
        ),
        migrations.RenameField(
            model_name='excelimport',
            old_name='data',
            new_name='date',
        ),
    ]
