# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_auto_20180927_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Goods')),
            ],
        ),
    ]
