# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_newgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='check',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проверрено'),
        ),
    ]
