# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_excelimport_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newgoods',
            options={'verbose_name': 'Новинка', 'verbose_name_plural': 'Новинки'},
        ),
    ]
