# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_auto_20180928_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerstock',
            options={'verbose_name': 'Баннер_акций', 'verbose_name_plural': 'Баннеры_акций'},
        ),
    ]
