# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20181001_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelImport',
        ),
    ]
