# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_delete_excelimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerStock',
        ),
    ]
