# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_auto_20181008_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='producers',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True, verbose_name='отображать'),
        ),
    ]
