# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_auto_20181011_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producers',
            name='visibility',
            field=models.BooleanField(db_index=True, default=False, verbose_name='отображать'),
        ),
    ]
