# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0031_auto_20181011_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='in_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
