# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_auto_20181012_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='goods/producers_photos'),
        ),
    ]
