# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lvlone',
            options={'ordering': ['name'], 'verbose_name_plural': 'Уровень: 1'},
        ),
        migrations.AlterModelOptions(
            name='lvlthree',
            options={'ordering': ['name'], 'verbose_name_plural': 'Уровень: 3'},
        ),
        migrations.AlterModelOptions(
            name='lvltwo',
            options={'ordering': ['name'], 'verbose_name_plural': 'Уровень: 2'},
        ),
        migrations.RemoveField(
            model_name='lvltwo',
            name='next_lvl',
        ),
        migrations.AddField(
            model_name='lvltwo',
            name='next_lvl',
            field=models.ManyToManyField(blank=True, null=True, to='filter.LvlThree', verbose_name='связь со следующим уровнем'),
        ),
    ]
