# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20181024_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvltwo',
            name='next_lvl',
            field=models.ManyToManyField(blank=True, to='filter.LvlThree', verbose_name='связь со следующим уровнем'),
        ),
    ]
