# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20181024_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvlone',
            name='next_lvl',
        ),
        migrations.AddField(
            model_name='lvlone',
            name='next_lvl',
            field=models.ManyToManyField(blank=True, to='filter.LvlTwo', verbose_name='связь со следующим уровнем'),
        ),
    ]
