# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20181024_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='LvlFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='уровень: 5')),
            ],
            options={
                'verbose_name_plural': 'Уровень: 5',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LvlFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='уровень: 4')),
                ('next_lvl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filter.LvlFive', verbose_name='связь со следующим уровнем')),
            ],
            options={
                'verbose_name_plural': 'Уровень: 4',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lvlthree',
            name='next_lvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filter.LvlFour', verbose_name='связь со следующим уровнем'),
        ),
    ]
