# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20181025_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvlfour',
            name='next_lvl',
        ),
        migrations.AddField(
            model_name='lvlfour',
            name='next_lvl',
            field=models.ManyToManyField(blank=True, to='filter.LvlFive', verbose_name='связь со следующим уровнем'),
        ),
        migrations.RemoveField(
            model_name='lvlthree',
            name='next_lvl',
        ),
        migrations.AddField(
            model_name='lvlthree',
            name='next_lvl',
            field=models.ManyToManyField(blank=True, to='filter.LvlFour', verbose_name='связь со следующим уровнем'),
        ),
    ]
