# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180925_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baskets',
            field=models.ManyToManyField(blank=True, to='basket.Cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
