# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20180925_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='baskets',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
