# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='banner/')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Баннер_акций',
                'verbose_name_plural': 'Баннеры_акций',
            },
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='excel/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('check', models.BooleanField(db_index=True, default=False, verbose_name='Проверрено')),
                ('code', models.IntegerField(blank=True, default=1, null=True, verbose_name='Код')),
                ('articul', models.IntegerField(blank=True, default=3, null=True, verbose_name='Артикул')),
                ('producer', models.IntegerField(blank=True, default=2, null=True, verbose_name='Производитель')),
                ('description', models.IntegerField(blank=True, default=4, null=True, verbose_name='Описание')),
                ('stock', models.IntegerField(blank=True, default=5, null=True, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, default=6, null=True, verbose_name='Розничная цена')),
                ('opt_1', models.IntegerField(blank=True, default=7, null=True, verbose_name='опт 1')),
                ('opt_2', models.IntegerField(blank=True, default=8, null=True, verbose_name='опт 2')),
                ('opt_3', models.IntegerField(blank=True, default=9, null=True, verbose_name='опт 3')),
                ('opt_4', models.IntegerField(blank=True, null=True, verbose_name='опт 4')),
                ('opt_5', models.IntegerField(blank=True, default=10, null=True, verbose_name='опт 5')),
                ('opt_6', models.IntegerField(blank=True, verbose_name='опт 6')),
                ('opt_7', models.IntegerField(blank=True, null=True, verbose_name='отп 7')),
                ('opt_8', models.IntegerField(blank=True, null=True, verbose_name='отп 8')),
                ('opt_9', models.IntegerField(blank=True, null=True, verbose_name='отп 9')),
                ('opt_10', models.IntegerField(blank=True, null=True, verbose_name='отп 10')),
                ('opt_11', models.IntegerField(blank=True, null=True, verbose_name='отп 11')),
                ('opt_12', models.IntegerField(blank=True, null=True, verbose_name='отп 12')),
                ('opt_13', models.IntegerField(blank=True, null=True, verbose_name='опт 13')),
                ('opt_14', models.IntegerField(blank=True, null=True, verbose_name='опт 14')),
                ('opt_15', models.IntegerField(blank=True, null=True, verbose_name='опт 15')),
                ('opt_16', models.IntegerField(blank=True, null=True, verbose_name='опт 16')),
                ('opt_17', models.IntegerField(blank=True, null=True, verbose_name='опт 17')),
                ('opt_18', models.IntegerField(blank=True, null=True, verbose_name='опт 18')),
                ('opt_19', models.IntegerField(blank=True, null=True, verbose_name='отп 19')),
                ('opt_20', models.IntegerField(blank=True, null=True, verbose_name='опт 20')),
            ],
            options={
                'verbose_name': 'Загрузить_эксел',
                'verbose_name_plural': 'Загрузить_эксели',
            },
        ),
        migrations.CreateModel(
            name='PdfCatalogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='pdf/pdf_img/')),
                ('file', models.FileField(upload_to='pdf/pdf_catalog/')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Каталог_PDF',
                'verbose_name_plural': 'Каталоги_PDF',
            },
        ),
    ]
