# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Баннер_акций',
                'verbose_name_plural': 'Баннеры_акций',
            },
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='excel/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('check', models.BooleanField(db_index=True, default=False, verbose_name='Проверрено')),
            ],
            options={
                'verbose_name': 'Загрузить_эксел',
                'verbose_name_plural': 'Загрузить_эксели',
            },
        ),
    ]
