# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelimport',
            name='opt_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 6'),
        ),
    ]
