# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_auto_20181019_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='opt_0',
            field=models.IntegerField(blank=True, null=True, verbose_name='опт 0'),
        ),
    ]
