# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_bannerstock_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCaralogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='pdf/pdf_img/')),
                ('file', models.FileField(upload_to='pdf/pdf_catalog/')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Каталог_PDF',
                'verbose_name_plural': 'Каталоги_PDF',
            },
        ),
    ]
