# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_excelimport_opt_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='filter_five',
            field=models.IntegerField(blank=True, null=True, verbose_name='фильтр ур. 5'),
        ),
        migrations.AddField(
            model_name='excelimport',
            name='filter_four',
            field=models.IntegerField(blank=True, null=True, verbose_name='фильтр ур. 4'),
        ),
        migrations.AddField(
            model_name='excelimport',
            name='filter_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='фильтр ур. 1'),
        ),
        migrations.AddField(
            model_name='excelimport',
            name='filter_three',
            field=models.IntegerField(blank=True, null=True, verbose_name='фильтр ур. 3'),
        ),
        migrations.AddField(
            model_name='excelimport',
            name='filter_two',
            field=models.IntegerField(blank=True, null=True, verbose_name='фильтр ур. 2'),
        ),
        migrations.AlterField(
            model_name='excelimport',
            name='price',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='Цена'),
        ),
    ]
