# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_pdfcaralogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfCaralogs',
            new_name='PdfCatalogs',
        ),
    ]
