# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchuserquery',
            name='query',
            field=models.PositiveIntegerField(),
        ),
    ]
