# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_meneger_third_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('mail_own', models.EmailField(blank=True, max_length=254, null=True, verbose_name='личная почта')),
                ('mail_work', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта рабочая')),
                ('phone_number_own', models.CharField(blank=True, max_length=30, null=True, verbose_name='личный номер тел')),
                ('phone_number_work', models.CharField(blank=True, max_length=30, null=True, verbose_name='рабочий номер тел')),
                ('customers', models.ManyToManyField(blank=True, to='basket.Customer', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.RemoveField(
            model_name='meneger',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Meneger',
        ),
    ]
