# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20181011_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (18, 18), (19, 12)], default=1),
        ),
    ]
