# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20180926_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (6, 6)], default=1),
        ),
    ]
